/* Generated by tools/make_audio.py: recorded audio for the listening sets. */
window.C1 = window.C1 || {};
C1.audio = {
 "listening": {
  "work": {
   "src": "audio/listening/work.mp3",
   "dur": 110.2,
   "marks": [
    0.0,
    6.72,
    14.52,
    22.64,
    32.49,
    38.76,
    46.07,
    54.03,
    62.04,
    66.16,
    70.16,
    77.96,
    86.56,
    88.71,
    99.03,
    103.38
   ]
  },
  "technology": {
   "src": "audio/listening/technology.mp3",
   "dur": 97.4,
   "marks": [
    0.0,
    25.05,
    43.33,
    68.76
   ]
  },
  "health": {
   "src": "audio/listening/health.mp3",
   "dur": 95.2,
   "marks": [
    0.0,
    9.23,
    24.91,
    28.19,
    33.35,
    38.55,
    53.97,
    57.84,
    74.01,
    77.65,
    89.87,
    92.96
   ]
  },
  "nature": {
   "src": "audio/listening/nature.mp3",
   "dur": 101.3,
   "marks": [
    0.0,
    11.26,
    46.9,
    68.29,
    70.61,
    80.82,
    92.4
   ]
  },
  "cities": {
   "src": "audio/listening/cities.mp3",
   "dur": 99.3,
   "marks": [
    0.0,
    5.5,
    17.1,
    29.17,
    36.21,
    43.75,
    51.92,
    55.75,
    62.09,
    78.61,
    85.24,
    89.59,
    97.01
   ]
  },
  "education": {
   "src": "audio/listening/education.mp3",
   "dur": 108.8,
   "marks": [
    0.0,
    24.02,
    51.07,
    75.95,
    91.01
   ]
  },
  "society": {
   "src": "audio/listening/society.mp3",
   "dur": 105.9,
   "marks": [
    0.0,
    5.9,
    11.83,
    20.32,
    31.75,
    41.77,
    57.87,
    71.84,
    74.76,
    83.03,
    93.95,
    96.18,
    102.24
   ]
  },
  "culture": {
   "src": "audio/listening/culture.mp3",
   "dur": 98.3,
   "marks": [
    0.0,
    22.29,
    27.11,
    32.03,
    43.91,
    53.44,
    58.11,
    63.86,
    70.34,
    78.14,
    84.35,
    90.49,
    95.47
   ]
  },
  "law-media": {
   "src": "audio/listening/law-media.mp3",
   "dur": 131.3,
   "marks": [
    0.0,
    10.75,
    25.42,
    42.52,
    55.68,
    72.74,
    75.13,
    87.22,
    96.28,
    111.98,
    117.63,
    126.22
   ]
  },
  "consumer-arts": {
   "src": "audio/listening/consumer-arts.mp3",
   "dur": 108.7,
   "marks": [
    0.0,
    4.84,
    11.08,
    24.8,
    32.96,
    37.42,
    44.92,
    51.91,
    65.24,
    74.5,
    76.58,
    83.19,
    92.55,
    100.18,
    107.77
   ]
  },
  "travel": {
   "src": "audio/listening/travel.mp3",
   "dur": 94.6,
   "marks": [
    0.0,
    3.39,
    15.86,
    17.99,
    30.08,
    32.83,
    47.48,
    49.33,
    67.08,
    71.28,
    85.52,
    87.54
   ]
  },
  "family": {
   "src": "audio/listening/family.mp3",
   "dur": 125.3,
   "marks": [
    0.0,
    14.78,
    32.05,
    50.29,
    52.23,
    65.85,
    80.44,
    89.65,
    92.12,
    100.52,
    108.37,
    110.28,
    120.71
   ]
  },
  "sport": {
   "src": "audio/listening/sport.mp3",
   "dur": 93.7,
   "marks": [
    0.0,
    28.5,
    51.6,
    74.49
   ]
  },
  "lecture-waiting": {
   "src": "audio/listening/lecture-waiting.mp3",
   "dur": 115.1,
   "marks": [
    0.0,
    11.84,
    21.4,
    38.72,
    52.59,
    68.68,
    77.17,
    82.56,
    89.07,
    98.43,
    102.18,
    108.51,
    111.11,
    113.9
   ]
  },
  "attitude-novel": {
   "src": "audio/listening/attitude-novel.mp3",
   "dur": 91.2,
   "marks": [
    0.0,
    4.86,
    10.19,
    13.15,
    23.53,
    26.28,
    36.13,
    37.43,
    45.53,
    48.28,
    56.61,
    62.86,
    69.13,
    74.65,
    80.08,
    84.5,
    88.07
   ]
  },
  "distractors-party": {
   "src": "audio/listening/distractors-party.mp3",
   "dur": 89.8,
   "marks": [
    0.0,
    5.35,
    10.72,
    16.54,
    20.08,
    29.57,
    32.76,
    36.28,
    39.13,
    44.03,
    48.68,
    56.7,
    63.28,
    70.6,
    75.13,
    77.41,
    80.05,
    83.5,
    87.75
   ]
  },
  "synthesis-market-street": {
   "src": "audio/listening/synthesis-market-street.mp3",
   "dur": 109.2,
   "marks": [
    0.0,
    7.33,
    16.18,
    20.79,
    34.48,
    40.0,
    51.9,
    59.25,
    64.05,
    72.62,
    83.39,
    87.88,
    94.81,
    100.97,
    106.67
   ]
  },
  "restaurant-mixup": {
   "src": "audio/listening/restaurant-mixup.mp3",
   "dur": 106.4,
   "marks": [
    0.0,
    3.11,
    7.09,
    13.19,
    17.6,
    20.8,
    36.43,
    43.32,
    47.22,
    50.05,
    54.76,
    61.18,
    65.66,
    69.13,
    76.12,
    82.28,
    84.97,
    93.26,
    103.86
   ]
  },
  "doctor-cough": {
   "src": "audio/listening/doctor-cough.mp3",
   "dur": 114.8,
   "marks": [
    0.0,
    3.66,
    11.08,
    14.56,
    24.32,
    26.54,
    31.95,
    34.51,
    45.25,
    46.91,
    51.6,
    63.8,
    67.68,
    84.27,
    86.72,
    93.71,
    101.92,
    105.05
   ]
  },
  "call-then-voicemail": {
   "src": "audio/listening/call-then-voicemail.mp3",
   "dur": 103.3,
   "marks": [
    0.0,
    4.28,
    9.27,
    14.79,
    23.11,
    27.84,
    33.66,
    35.42,
    45.94,
    55.38,
    58.41,
    66.68,
    74.82,
    83.54,
    85.1
   ]
  },
  "radio-foxes": {
   "src": "audio/listening/radio-foxes.mp3",
   "dur": 114.9,
   "marks": [
    0.0,
    13.67,
    16.01,
    23.18,
    37.19,
    39.81,
    51.17,
    54.37,
    65.75,
    68.69,
    80.21,
    84.39,
    97.65,
    100.38,
    111.06,
    113.66
   ]
  },
  "panel-remote-study": {
   "src": "audio/listening/panel-remote-study.mp3",
   "dur": 110.7,
   "marks": [
    0.0,
    7.63,
    19.83,
    29.87,
    41.79,
    46.89,
    52.92,
    63.78,
    70.98,
    75.61,
    80.23,
    88.01,
    93.7,
    98.44,
    105.71,
    108.96
   ]
  },
  "interview-founder": {
   "src": "audio/listening/interview-founder.mp3",
   "dur": 104.9,
   "marks": [
    0.0,
    9.25,
    13.28,
    16.95,
    27.22,
    29.25,
    41.19,
    42.87,
    55.15,
    57.41,
    67.07,
    69.32,
    81.46,
    83.78,
    94.68,
    97.72
   ]
  },
  "friends-documentary": {
   "src": "audio/listening/friends-documentary.mp3",
   "dur": 104.0,
   "marks": [
    0.0,
    5.29,
    16.95,
    21.13,
    27.63,
    34.64,
    45.18,
    54.37,
    61.15,
    65.3,
    71.59,
    80.84,
    91.72,
    93.42,
    102.16
   ]
  },
  "museum-tour": {
   "src": "audio/listening/museum-tour.mp3",
   "dur": 108.2,
   "marks": [
    0.0,
    15.04,
    21.76,
    24.8,
    34.59,
    37.21,
    45.16,
    47.57,
    60.32,
    69.75,
    77.23,
    80.68,
    91.04,
    94.41,
    96.69
   ]
  },
  "radio-teen-sleep": {
   "src": "audio/listening/radio-teen-sleep.mp3",
   "dur": 122.1,
   "marks": [
    0.0,
    11.3,
    28.09,
    33.05,
    51.63,
    55.38,
    73.21,
    75.66,
    87.43,
    90.03,
    109.07,
    113.02
   ]
  },
  "debate-urban-farming": {
   "src": "audio/listening/debate-urban-farming.mp3",
   "dur": 134.1,
   "marks": [
    0.0,
    13.29,
    26.36,
    35.93,
    39.23,
    49.53,
    56.65,
    59.38,
    71.19,
    75.63,
    79.95,
    83.36,
    93.96,
    98.71,
    101.35,
    116.5,
    122.57,
    124.81,
    129.39
   ]
  },
  "lecture-memory-myths": {
   "src": "audio/listening/lecture-memory-myths.mp3",
   "dur": 124.8,
   "marks": [
    0.0,
    10.06,
    15.29,
    33.76,
    37.21,
    47.59,
    51.36,
    66.51,
    70.11,
    78.23,
    82.0,
    94.28,
    97.29,
    103.98,
    106.17,
    115.86,
    118.5
   ]
  },
  "interview-architect": {
   "src": "audio/listening/interview-architect.mp3",
   "dur": 121.3,
   "marks": [
    0.0,
    10.09,
    14.86,
    18.08,
    28.8,
    31.21,
    36.6,
    39.28,
    48.84,
    51.67,
    60.8,
    63.29,
    74.5,
    77.85,
    88.51,
    90.58,
    101.71,
    104.67,
    110.72,
    112.83
   ]
  },
  "meeting-budget-cuts": {
   "src": "audio/listening/meeting-budget-cuts.mp3",
   "dur": 106.3,
   "marks": [
    0.0,
    11.28,
    17.95,
    24.26,
    28.44,
    31.96,
    40.42,
    43.25,
    48.92,
    54.7,
    60.77,
    66.76,
    70.73,
    75.27,
    85.14,
    89.74,
    95.26,
    97.84,
    103.23
   ]
  }
 }
};
