/* Generated by tools/make_audio.py: recorded audio for the listening sets. */
window.C1 = window.C1 || {};
C1.audio = {
 "listening": {
  "work": {
   "src": "audio/listening/work.mp3",
   "dur": 110.2,
   "marks": [
    0.0,
    6.72,
    14.52,
    22.64,
    32.49,
    38.76,
    46.07,
    54.03,
    62.04,
    66.16,
    70.16,
    77.96,
    86.56,
    88.71,
    99.03,
    103.38
   ]
  },
  "technology": {
   "src": "audio/listening/technology.mp3",
   "dur": 97.4,
   "marks": [
    0.0,
    25.05,
    43.33,
    68.76
   ]
  },
  "health": {
   "src": "audio/listening/health.mp3",
   "dur": 95.2,
   "marks": [
    0.0,
    9.23,
    24.91,
    28.19,
    33.35,
    38.55,
    53.97,
    57.84,
    74.01,
    77.65,
    89.87,
    92.96
   ]
  },
  "nature": {
   "src": "audio/listening/nature.mp3",
   "dur": 101.3,
   "marks": [
    0.0,
    11.26,
    46.9,
    68.29,
    70.61,
    80.82,
    92.4
   ]
  },
  "cities": {
   "src": "audio/listening/cities.mp3",
   "dur": 99.3,
   "marks": [
    0.0,
    5.5,
    17.1,
    29.17,
    36.21,
    43.75,
    51.92,
    55.75,
    62.09,
    78.61,
    85.24,
    89.59,
    97.01
   ]
  },
  "education": {
   "src": "audio/listening/education.mp3",
   "dur": 108.8,
   "marks": [
    0.0,
    24.02,
    51.07,
    75.95,
    91.01
   ]
  },
  "society": {
   "src": "audio/listening/society.mp3",
   "dur": 105.9,
   "marks": [
    0.0,
    5.9,
    11.83,
    20.32,
    31.75,
    41.77,
    57.87,
    71.84,
    74.76,
    83.03,
    93.95,
    96.18,
    102.24
   ]
  },
  "culture": {
   "src": "audio/listening/culture.mp3",
   "dur": 98.3,
   "marks": [
    0.0,
    22.29,
    27.11,
    32.03,
    43.91,
    53.44,
    58.11,
    63.86,
    70.34,
    78.14,
    84.35,
    90.49,
    95.47
   ]
  },
  "law-media": {
   "src": "audio/listening/law-media.mp3",
   "dur": 131.3,
   "marks": [
    0.0,
    10.75,
    25.42,
    42.52,
    55.68,
    72.74,
    75.13,
    87.22,
    96.28,
    111.98,
    117.63,
    126.22
   ]
  },
  "consumer-arts": {
   "src": "audio/listening/consumer-arts.mp3",
   "dur": 108.7,
   "marks": [
    0.0,
    4.84,
    11.08,
    24.8,
    32.96,
    37.42,
    44.92,
    51.91,
    65.24,
    74.5,
    76.58,
    83.19,
    92.55,
    100.18,
    107.77
   ]
  },
  "travel": {
   "src": "audio/listening/travel.mp3",
   "dur": 94.6,
   "marks": [
    0.0,
    3.39,
    15.86,
    17.99,
    30.08,
    32.83,
    47.48,
    49.33,
    67.08,
    71.28,
    85.52,
    87.54
   ]
  },
  "family": {
   "src": "audio/listening/family.mp3",
   "dur": 125.3,
   "marks": [
    0.0,
    14.78,
    32.05,
    50.29,
    52.23,
    65.85,
    80.44,
    89.65,
    92.12,
    100.52,
    108.37,
    110.28,
    120.71
   ]
  },
  "sport": {
   "src": "audio/listening/sport.mp3",
   "dur": 93.7,
   "marks": [
    0.0,
    28.5,
    51.6,
    74.49
   ]
  }
 }
};
