"""Generate one short recording per vocabulary item with Kokoro (open-source neural text-to-speech, Apache-2.0).

Output: audio/vocab/<slug>.mp3 and audio/vocab_manifest.js (C1.vocabAudio: the slugs that exist).
The phrases are the keys of C1.ipa in data/ipa.js. Same requirements as tools/make_audio.py.
Usage:  python tools/make_vocab_audio.py <path to kokoro-v1.0.onnx> <path to voices-v1.0.bin>
Already generated clips are kept, so the script can be stopped and run again.
"""
import json, re, subprocess, sys, pathlib, tempfile, os, shutil
import soundfile as sf
from kokoro_onnx import Kokoro
try:
    import imageio_ffmpeg
    FFMPEG = imageio_ffmpeg.get_ffmpeg_exe()
except ImportError:
    FFMPEG = shutil.which('ffmpeg')

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / 'audio' / 'vocab'
OUT.mkdir(parents=True, exist_ok=True)

def slug(p):  # must match slug() in js/app.js
    return re.sub(r'^-|-$', '', re.sub(r'[^a-z0-9]+', '-', p.lower()))

def spoken(p):  # must match spoken() in js/app.js
    t = re.sub(r'\([^)]*\)', ' ', p)
    t = re.sub(r'\bsb\b', 'somebody', t); t = re.sub(r'\bsth\b', 'something', t); t = t.replace('/', ' ')
    return re.sub(r'\s+', ' ', t).strip()

src = (ROOT / 'data' / 'ipa.js').read_text(encoding='utf8')
phrases = list(json.loads(src[src.index('C1.ipa = ') + 9:src.rindex(';')]).keys())
if not FFMPEG: sys.exit('ffmpeg not found: pip install imageio-ffmpeg')
kokoro = Kokoro(sys.argv[1], sys.argv[2])
done = []
for n, p in enumerate(phrases, 1):
    f = OUT / (slug(p) + '.mp3')
    if not f.exists():
        samples, rate = kokoro.create(spoken(p), voice='bf_emma', speed=0.9, lang='en-gb')
        with tempfile.TemporaryDirectory() as td:
            wav = os.path.join(td, 'a.wav'); sf.write(wav, samples, rate)
            subprocess.check_call([FFMPEG, '-y', '-loglevel', 'error', '-i', wav, '-af', 'silenceremove=start_periods=1:start_threshold=-50dB,areverse,silenceremove=start_periods=1:start_threshold=-50dB,areverse', '-ac', '1', '-codec:a', 'libmp3lame', '-b:a', '32k', str(f)])
    done.append(slug(p))
    if n % 50 == 0: print(n, 'of', len(phrases), flush=True)
(ROOT / 'audio' / 'vocab_manifest.js').write_text('window.C1 = window.C1 || {};\n/* generated by tools/make_vocab_audio.py: vocabulary items that have a recording in audio/vocab */\nC1.vocabAudio = ' + json.dumps(sorted(set(done))) + ';\n', encoding='utf8')
print('ok', len(done))
