"""Generate the listening audio with Kokoro (open-source neural text-to-speech, Apache-2.0).

Output: audio/listening/<id>.mp3 and audio/manifest.js (durations and the start time of every line).
Needs Python 3.10-3.12 with:  pip install kokoro-onnx soundfile numpy imageio-ffmpeg
(imageio-ffmpeg ships an ffmpeg binary; a normal ffmpeg on the PATH works too.)
and the two model files from https://github.com/thewh1teagle/kokoro-onnx/releases (model-files-v1.0):
  kokoro-v1.0.onnx  and  voices-v1.0.bin
Usage:  python tools/make_audio.py <path to kokoro-v1.0.onnx> <path to voices-v1.0.bin> [set id ...]
"""
import json, subprocess, sys, pathlib, tempfile, os, shutil
import numpy as np
import soundfile as sf
from kokoro_onnx import Kokoro

try:
    import imageio_ffmpeg
    FFMPEG = imageio_ffmpeg.get_ffmpeg_exe()
except ImportError:
    FFMPEG = shutil.which('ffmpeg')


ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / 'audio' / 'listening'

# Voice per speaker: the gender of each character name decides the pool; every speaker in a recording gets a different voice.
FEMALE = {'Gemma', 'Carol', 'Isla', 'Anna', 'Rachel', 'Helen', 'Priya', 'Sofia', 'Rosa', 'Nadia', 'Lena', 'Marta', 'Dr Hill', 'Presenter', 'Guide'}
MALE = {'Raj', 'Jamal', 'Dev', 'Mark', 'Tom', 'Luis', 'Dan', 'James', 'Ben', 'Colin', 'Omar', 'Joel', 'Dr Morgan'}
POOLS = {'f': ['bf_emma', 'bf_isabella', 'bf_alice', 'bf_lily'], 'm': ['bm_george', 'bm_lewis', 'bm_daniel', 'bm_fable']}


def gender(name, taken):
    if name in FEMALE: return 'f'
    if name in MALE: return 'm'
    return 'f' if len(taken) % 2 == 0 else 'm'


def main():
    if len(sys.argv) < 3: sys.exit(__doc__)
    model, voices, only = sys.argv[1], sys.argv[2], set(sys.argv[3:])
    sets = json.loads(subprocess.check_output(['node', str(ROOT / 'tools' / 'dump-listening.js')], cwd=ROOT))
    kokoro = Kokoro(model, voices)
    OUT.mkdir(parents=True, exist_ok=True)
    manifest = {}
    for s in sets:
        if only and s['id'] not in only: continue
        assign, used = {}, {'f': 0, 'm': 0}
        for line in s['script']:
            who = line.get('who') or ''
            if who not in assign:
                g = gender(who, assign)
                pool = POOLS[g]
                assign[who] = pool[used[g] % len(pool)]
                used[g] += 1
        sr, chunks, marks, t, prev = 24000, [], [], 0.0, None
        for line in s['script']:
            who = line.get('who') or ''
            gap = 0.0 if prev is None else (0.55 if who != prev else 0.3)
            if gap:
                chunks.append(np.zeros(int(sr * gap), dtype=np.float32)); t += gap
            samples, rate = kokoro.create(line['text'], voice=assign[who], speed=0.95, lang='en-gb')
            assert rate == sr
            marks.append(round(t, 2))
            chunks.append(samples.astype(np.float32)); t += len(samples) / sr
            prev = who
        audio = np.concatenate(chunks)
        if not FFMPEG: sys.exit('ffmpeg not found: pip install imageio-ffmpeg')
        with tempfile.TemporaryDirectory() as tmp:
            wav = os.path.join(tmp, 'a.wav')
            sf.write(wav, audio, sr)
            subprocess.check_call([FFMPEG, '-y', '-loglevel', 'error', '-i', wav, '-ac', '1', '-codec:a', 'libmp3lame', '-b:a', '40k', str(OUT / (s['id'] + '.mp3'))])
        manifest[s['id']] = {'src': 'audio/listening/' + s['id'] + '.mp3', 'dur': round(t, 1), 'marks': marks}
        print(s['id'], assign, round(t, 1), 's', flush=True)
    existing = {}
    mf = ROOT / 'audio' / 'manifest.js'
    if only and mf.exists():
        txt = mf.read_text(encoding='utf-8')
        existing = json.loads(txt[txt.index('C1.audio =') + len('C1.audio ='):].rstrip().rstrip(';')).get('listening', {})
    existing.update(manifest)
    mf.write_text('/* Generated by tools/make_audio.py: recorded audio for the listening sets. */\nwindow.C1 = window.C1 || {};\nC1.audio = ' + json.dumps({'listening': existing}, indent=1) + ';\n', encoding='utf-8')


main()
